### ISSUE TITLE
unauthenticated request

### ISSUE THREAD

**Issue by ghost** [koalagang/crunchyroll-cli#1]
```
jenny :: /tmp » crunchyroll-cli -p black clover
Enter crunchyroll username: xxxxx@xxxxxx.xx
Enter crunchyroll password: 
[cli][info] Found matching plugin crunchyroll for URL https://crunchyroll.com/black-clover/episode-8-go-go-first-mission-748947
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 11, in <module>
    load_entry_point('streamlink==1.3.1', 'console_scripts', 'streamlink')()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 1038, in main
    handle_url()
  File "/usr/share/streamlink/streamlink_cli/main.py", line 578, in handle_url
    streams = fetch_streams(plugin)
  File "/usr/share/streamlink/streamlink_cli/main.py", line 457, in fetch_streams
    return plugin.streams(stream_types=args.stream_types,
  File "/usr/lib/python3/dist-packages/streamlink/plugin/plugin.py", line 317, in streams
    ostreams = self._get_streams()
  File "/usr/lib/python3/dist-packages/streamlink/plugins/crunchyroll.py", line 306, in _get_streams
    api = self._create_api()
  File "/usr/lib/python3/dist-packages/streamlink/plugins/crunchyroll.py", line 365, in _create_api
    api.start_session()
  File "/usr/lib/python3/dist-packages/streamlink/plugins/crunchyroll.py", line 197, in start_session
    self.session_id = self._api_call("start_session", params, schema=_session_schema)
  File "/usr/lib/python3/dist-packages/streamlink/plugins/crunchyroll.py", line 173, in _api_call
    raise CrunchyrollAPIError(err_msg, err_code)
streamlink.plugin.crunchyroll.CrunchyrollAPIError: Unauthenticated request
AV: 00:03:40 / 00:23:53 (15%) A-V:  0.000 Cache: 15s/16MB
```

fresh install (using the method utilizing make) and tried the premium option.. 
It gave me the above.

`note: email is redacted`

**Comment by koalagang** [comment]
I tested this myself and it seems to work fine for me both with crunchyroll-cli and with streamlink directly.
You can also test this on your system by using streamlink directly without crunchyroll-cli with this command:

`streamlink 'https://crunchyroll.com/black-clover/episode-8-go-go-first-mission-748947' best --player mpv --crunchyroll-username "$your-username"`

You'll be prompted for your password.
That will probably create the same error (but might be worth testing, in case the issue is on crunchyroll-cli's end) but I think your issue might be to do with the version of streamlink you have installed. Could you please specify which version you are using? 

You can find this by doing:

`streamlink --version`

You can also check what crunchyroll-cli version you are using with:

`crunchyroll-cli -v`

**Comment by ghost** [comment]
I reinstalled it again and works...
Thanks anyways!!
and thanks for making this lovely program!
